# -*- coding: utf-8 -*-
"""Sembol evreni ve sektor haritasi.

SEKTOR haritasi elle derlenmistir; yanlis gordugun yeri duzeltebilirsin.
Haritada olmayan sembol otomatik olarak "DIGER" sayilir - sistem kirilmaz.
"""

SEMBOLLER = (
 "THYAO ASELS EREGL SISE TUPRS FROTO GARAN AKBNK BIMAS KCHOL SAHOL PETKM TCELL "
 "ISCTR YKBNK TOASO SASA HEKTS KRDMD ARCLK ASTOR KONTR ENKAI PGSUS TAVHL MGROS "
 "SOKM ULKER AEFES CCOLA OYAKC CIMSA AKSEN ZOREN ALARK DOAS VESTL TTKOM TTRAK "
 "OTKAR GUBRF EKGYO ISGYO AKSA BRSAN SMRTG GESAN EUPWR YEOTK TUKAS "
 "HALKB VAKBN TSKB ISDMR AYGAZ ALKIM BAGFS DEVA ECILC SELEC LOGO KAREL INDES "
 "MAVI BIZIM ENJSA AYDEM GWIND ODAS KARSN EGEEN TKFEN KORDS VESBE DOHOL AGHOL "
 "TATGD PNSUT BRISA GOODY BUCIM KONYA GOLTS ANHYT AGESA TURSG AKGRT JANTS "
 "TMSN NETAS ALCTL YATAS MPARK CLEBI CWENE "
 "ADEL AGROT AHGAZ AKCNS ALBRK ALTNY ANSGR BERA BFREN BINHO BRYAT BTCIM "
 "CANTE ENERY FENER GLYHO IZENR KCAER KLSER LMKDC MAGEN MIATK PASEU PEKGY "
 "QUAGR REEDR SAYAS SDTTR SKBNK TABGD TUREX VAKKO ISMEN").split()

SEKTOR = {
    # Banka & finans
    "GARAN": "BANKA", "AKBNK": "BANKA", "ISCTR": "BANKA", "YKBNK": "BANKA",
    "HALKB": "BANKA", "VAKBN": "BANKA", "TSKB": "BANKA", "ALBRK": "BANKA",
    "SKBNK": "BANKA", "ISMEN": "FINANS", "ANHYT": "SIGORTA", "AGESA": "SIGORTA",
    "TURSG": "SIGORTA", "AKGRT": "SIGORTA", "ANSGR": "SIGORTA",
    # Holding
    "KCHOL": "HOLDING", "SAHOL": "HOLDING", "ALARK": "HOLDING", "DOHOL": "HOLDING",
    "AGHOL": "HOLDING", "GLYHO": "HOLDING", "BERA": "HOLDING", "ENKAI": "HOLDING",
    "BRYAT": "HOLDING",
    # Sanayi & metal
    "EREGL": "METAL", "ISDMR": "METAL", "KRDMD": "METAL", "BRSAN": "METAL",
    "KCAER": "METAL", "SAYAS": "MAKINE", "TMSN": "MAKINE", "EGEEN": "MAKINE",
    "BFREN": "OTOMOTIV_YAN", "JANTS": "OTOMOTIV_YAN", "KORDS": "OTOMOTIV_YAN",
    "BRISA": "OTOMOTIV_YAN", "GOODY": "OTOMOTIV_YAN",
    # Otomotiv
    "FROTO": "OTOMOTIV", "TOASO": "OTOMOTIV", "TTRAK": "OTOMOTIV",
    "OTKAR": "OTOMOTIV", "KARSN": "OTOMOTIV", "DOAS": "OTOMOTIV",
    # Kimya & petrol
    "TUPRS": "PETROL", "PETKM": "KIMYA", "SASA": "KIMYA", "AKSA": "KIMYA",
    "ALKIM": "KIMYA", "BAGFS": "GUBRE", "GUBRF": "GUBRE", "HEKTS": "KIMYA",
    "AYGAZ": "PETROL",
    # Cimento & insaat
    "CIMSA": "CIMENTO", "AKCNS": "CIMENTO", "OYAKC": "CIMENTO", "BUCIM": "CIMENTO",
    "BTCIM": "CIMENTO", "KONYA": "CIMENTO", "GOLTS": "CIMENTO", "QUAGR": "CIMENTO",
    "SISE": "CAM", "TKFEN": "TAAHHUT", "LMKDC": "TAAHHUT",
    # Enerji
    "AKSEN": "ENERJI", "ZOREN": "ENERJI", "ENJSA": "ENERJI", "AYDEM": "ENERJI",
    "GWIND": "ENERJI", "ODAS": "ENERJI", "CANTE": "ENERJI", "ENERY": "ENERJI",
    "IZENR": "ENERJI", "MAGEN": "ENERJI", "AHGAZ": "ENERJI", "SMRTG": "ENERJI",
    "EUPWR": "ENERJI", "GESAN": "ENERJI", "ASTOR": "ENERJI", "CWENE": "ENERJI",
    "ALTNY": "ENERJI", "REEDR": "ENERJI",
    # Perakende & gida
    "BIMAS": "PERAKENDE", "MGROS": "PERAKENDE", "SOKM": "PERAKENDE",
    "BIZIM": "PERAKENDE", "MAVI": "PERAKENDE", "VAKKO": "PERAKENDE",
    "ULKER": "GIDA", "AEFES": "ICECEK", "CCOLA": "ICECEK", "TATGD": "GIDA",
    "PNSUT": "GIDA", "TUKAS": "GIDA", "TABGD": "GIDA", "PASEU": "GIDA",
    "AGROT": "TARIM",
    # Ulastirma
    "THYAO": "ULASTIRMA", "PGSUS": "ULASTIRMA", "TAVHL": "ULASTIRMA",
    "CLEBI": "ULASTIRMA", "TUREX": "ULASTIRMA",
    # Teknoloji & savunma
    "ASELS": "SAVUNMA", "SDTTR": "SAVUNMA", "KAREL": "TEKNOLOJI",
    "LOGO": "TEKNOLOJI", "NETAS": "TEKNOLOJI", "ALCTL": "TEKNOLOJI",
    "INDES": "TEKNOLOJI", "MIATK": "TEKNOLOJI", "KONTR": "TEKNOLOJI",
    "TCELL": "ILETISIM", "TTKOM": "ILETISIM",
    # Dayanikli tuketim
    "ARCLK": "BEYAZ_ESYA", "VESTL": "BEYAZ_ESYA", "VESBE": "BEYAZ_ESYA",
    "YATAS": "MOBILYA", "ADEL": "TUKETIM", "KLSER": "TUKETIM",
    # GYO & saglik & diger
    "EKGYO": "GYO", "ISGYO": "GYO", "PEKGY": "GYO", "BINHO": "GYO",
    "MPARK": "SAGLIK", "DEVA": "ILAC", "ECILC": "ILAC", "SELEC": "ILAC",
    "FENER": "DIGER", "YEOTK": "ENERJI",
}


def sektor(sym):
    return SEKTOR.get(sym, "DIGER")


def sektor_gruplari(semboller):
    g = {}
    for s in semboller:
        g.setdefault(sektor(s), []).append(s)
    return g
